### ISSUE TITLE
Несовместимость с гемом awesome_print

### ISSUE THREAD

**Issue by melnik88** [awinogradov/bem-on-rails#10]
Антон, посмотри пожалуйста, при установке bemonrails вместе с гемом awesome_print возникает ошибка uninitialized constant Bemonrails::BemRenderHelper.

Rails 4.0.0
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.1.0]

**Comment by awinogradov** [comment]
Понял тебя, посмотрю
